/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ChemistRole;

import Business.Queue.AppointmentVisitRequest;
import Business.Validations.StringThenSpaceVerifier;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Zeppelin
 */
public class ChemistProcessDrugJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private AppointmentVisitRequest request;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ChemistProcessDrugJPanel(JPanel userProcessContainer, AppointmentVisitRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        
         
        addStringThenSpaceVerifiers();
        checkBlankInput();
    }

    
     private Boolean checkBlankInput()
    {
        if(resultJTextField.getText().length()==0)
            {
                return false;
            }
        else
        {
            return true;
        }
    }  
    
    private void addStringThenSpaceVerifiers(){
        InputVerifier stringThenSpaceVerifier = new StringThenSpaceVerifier();
        resultJTextField.setInputVerifier(stringThenSpaceVerifier);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Result");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        resultJTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        resultJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultJTextFieldActionPerformed(evt);
            }
        });
        add(resultJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 88, -1));

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("PROCESS REQUEST");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ChemistToDoctorJPanel dwjp = (ChemistToDoctorJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
     if(checkBlankInput()){
        request.setStatus2("Completed");
        request.setPrescriptionResult(resultJTextField.getText());
        JOptionPane.showMessageDialog(null,"Submitted,","Information", JOptionPane.INFORMATION_MESSAGE);
     }
     else{
         JOptionPane.showMessageDialog(null,"You cannot leave it blank,","Warning", JOptionPane.WARNING_MESSAGE);
        
     }
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void resultJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultJTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField resultJTextField;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
