/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ChemistRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Zeppelin
 */

public class ChemistWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private Organization org;
    private Network network;
   
    
    public ChemistWorkAreaJPanel(JPanel container, UserAccount userAccount,
        Organization organization, EcoSystem business, Enterprise enterprise) {
        
        initComponents();
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        userProcessContainer = container;
        this.org = organization;
        system = business;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        notifyPatientJButton = new javax.swing.JButton();
        processDoctorJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DOCTOR WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 32, -1, -1));

        notifyPatientJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        notifyPatientJButton.setText("Notify Patient for Drugs");
        notifyPatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifyPatientJButtonActionPerformed(evt);
            }
        });
        add(notifyPatientJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 199, 200, 42));

        processDoctorJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        processDoctorJButton.setText("Process Doctor's Request");
        processDoctorJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processDoctorJButtonActionPerformed(evt);
            }
        });
        add(processDoctorJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 128, 200, 42));
    }// </editor-fold>//GEN-END:initComponents

    private void processDoctorJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processDoctorJButtonActionPerformed
        
        ChemistToDoctorJPanel ctdjp = new ChemistToDoctorJPanel(userProcessContainer, userAccount, org, system, enterprise);
        userProcessContainer.add("ChemistToDoctorJPanel", ctdjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_processDoctorJButtonActionPerformed

    private void notifyPatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifyPatientJButtonActionPerformed
       
        ChemistToPatientJPanel ctpjp = new ChemistToPatientJPanel(userProcessContainer, userAccount, org, system, enterprise);
        userProcessContainer.add("ChemistToPatientJPanel", ctpjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_notifyPatientJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton notifyPatientJButton;
    private javax.swing.JButton processDoctorJButton;
    // End of variables declaration//GEN-END:variables
}
