/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.PatientOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Zeppelin
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    
    public PatientWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        appointmentJButton = new javax.swing.JButton();
        medicalDetailsJButton = new javax.swing.JButton();
        medicinesAndTestsJButton = new javax.swing.JButton();
        pathologyUpadtesJButton = new javax.swing.JButton();
        pharmacyUpdatesJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("    PATIENT WORK AREA");

        appointmentJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        appointmentJButton.setText("Book Appointment");
        appointmentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentJButtonActionPerformed(evt);
            }
        });

        medicalDetailsJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        medicalDetailsJButton.setText("Appointment Visit Details");
        medicalDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalDetailsJButtonActionPerformed(evt);
            }
        });

        medicinesAndTestsJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        medicinesAndTestsJButton.setText("Medicine and Test Details");
        medicinesAndTestsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicinesAndTestsJButtonActionPerformed(evt);
            }
        });

        pathologyUpadtesJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pathologyUpadtesJButton.setText("View Updates From Pathology");
        pathologyUpadtesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathologyUpadtesJButtonActionPerformed(evt);
            }
        });

        pharmacyUpdatesJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pharmacyUpdatesJButton.setText("View Updates From Pharmacy");
        pharmacyUpdatesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacyUpdatesJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pathologyUpadtesJButton)
                    .addComponent(pharmacyUpdatesJButton)
                    .addComponent(medicinesAndTestsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicalDetailsJButton)
                    .addComponent(appointmentJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {appointmentJButton, jLabel1, medicalDetailsJButton, medicinesAndTestsJButton, pathologyUpadtesJButton, pharmacyUpdatesJButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(appointmentJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(medicalDetailsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(medicinesAndTestsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(pathologyUpadtesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(pharmacyUpdatesJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {appointmentJButton, jLabel1, medicalDetailsJButton, medicinesAndTestsJButton, pathologyUpadtesJButton, pharmacyUpdatesJButton});

    }// </editor-fold>//GEN-END:initComponents

    private void medicalDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalDetailsJButtonActionPerformed
        // TODO add your handling code here:
        
        MedicalDetailsJPanel mdjp = new MedicalDetailsJPanel
        (userProcessContainer, userAccount, organization, enterprise, system);
        userProcessContainer.add("MedicalDetailsJPanel", mdjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_medicalDetailsJButtonActionPerformed

    private void medicinesAndTestsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicinesAndTestsJButtonActionPerformed
        // TODO add your handling code here:
      MedicinesAndTestsDetailsJPanel matdjp = new MedicinesAndTestsDetailsJPanel
      (userProcessContainer, userAccount, organization, enterprise, system);
      userProcessContainer.add("MedicinesAndTestsDetailsJPanel", matdjp);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_medicinesAndTestsJButtonActionPerformed

    private void appointmentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentJButtonActionPerformed
        // TODO add your handling code here:
     PatientToDoctorRequestJPanel ptdrjp = new PatientToDoctorRequestJPanel
     (userProcessContainer, userAccount, organization, enterprise, system);
     userProcessContainer.add("PatientToDoctorRequestJPanel", ptdrjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_appointmentJButtonActionPerformed

    private void pharmacyUpdatesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacyUpdatesJButtonActionPerformed
        // TODO add your handling code here:
        PatientToChemistJPanel ptcjp = new PatientToChemistJPanel
        (userProcessContainer, userAccount, organization, enterprise, system);
     userProcessContainer.add("PatientToChemistJPanel", ptcjp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_pharmacyUpdatesJButtonActionPerformed

    private void pathologyUpadtesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathologyUpadtesJButtonActionPerformed
        // TODO add your handling code here:
         PatientToLabAssistantJPanel ptlajp = new PatientToLabAssistantJPanel
        (userProcessContainer, userAccount, organization, system);
     userProcessContainer.add("PatientToLabAssistantJPanel", ptlajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
        
    }//GEN-LAST:event_pathologyUpadtesJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointmentJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton medicalDetailsJButton;
    private javax.swing.JButton medicinesAndTestsJButton;
    private javax.swing.JButton pathologyUpadtesJButton;
    private javax.swing.JButton pharmacyUpdatesJButton;
    // End of variables declaration//GEN-END:variables
}
