/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Zeppelin
 */

public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
  //  private DoctorOrganization doctorOrg;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    private Organization org;
    private Network network;
   
    
    public DoctorWorkAreaJPanel(JPanel container, UserAccount userAccount,
        Organization organization, Enterprise enterprise,EcoSystem business, Network network) {
        
        initComponents();
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        userProcessContainer = container;
        this.org = organization;
        system = business;
        this.network = network;
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        appointmentJButton = new javax.swing.JButton();
        requestDrugJButton = new javax.swing.JButton();
        requestJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DOCTOR WORK AREA");

        appointmentJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        appointmentJButton.setText("Process Appointment");
        appointmentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentJButtonActionPerformed(evt);
            }
        });

        requestDrugJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        requestDrugJButton.setText("Request Drug");
        requestDrugJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestDrugJButtonActionPerformed(evt);
            }
        });

        requestJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        requestJButton.setText("Request Test");
        requestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(appointmentJButton)
                    .addComponent(requestDrugJButton)
                    .addComponent(requestJButton)
                    .addComponent(jLabel1))
                .addContainerGap(405, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {appointmentJButton, jLabel1, requestDrugJButton, requestJButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(appointmentJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(requestDrugJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(requestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {appointmentJButton, jLabel1, requestDrugJButton, requestJButton});

    }// </editor-fold>//GEN-END:initComponents

    private void appointmentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentJButtonActionPerformed
        // TODO add your handling code here:
        
        DoctorToPatientProcessJPanel dajp = new DoctorToPatientProcessJPanel(userProcessContainer, userAccount, org, system);
        userProcessContainer.add("DoctorAppointmentJPanel", dajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_appointmentJButtonActionPerformed

    private void requestDrugJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestDrugJButtonActionPerformed
        // TODO add your handling code here:
        DoctorToChemistRequestJPanel dtpjp = new DoctorToChemistRequestJPanel(userProcessContainer, userAccount, org, enterprise, system, network);
        userProcessContainer.add("DoctorToChemistRequestJPanel", dtpjp);        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_requestDrugJButtonActionPerformed

    private void requestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestJButtonActionPerformed
        // TODO add your handling code here:
        
        DoctorToLabAssistantRequestJPanel dtlarjp= new 
        DoctorToLabAssistantRequestJPanel(userProcessContainer, userAccount, 
                org, enterprise, system, network);
        userProcessContainer.add("DoctorToPharmacyRequestJPanel", dtlarjp);        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointmentJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton requestDrugJButton;
    private javax.swing.JButton requestJButton;
    // End of variables declaration//GEN-END:variables
}
