/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;


import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.Organization.ChemistOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Queue.AppointmentVisitRequest;
import Business.Queue.WorkRequest;
import Business.Validations.NumericVerifier;
import Business.Validations.StringThenSpaceVerifier;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zeppelin
 */
public class RequestDrugJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private Network network;
    private Organization org;
    
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestDrugJPanel(JPanel userProcessContainer, UserAccount account,
            Enterprise enterprise,Organization org, EcoSystem business, Network network) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        userAccount = account;
        this.business = business;
        this.org=org;
       
      
        checkBlankInput();
        populatepatientJTable();
        addStringThenSpaceVerifiers();
        addIntegerVerifiers();
    }
 
     private Boolean checkBlankInput()
    {
        if(mOneJTextField.getText().length()==0
            ||mTwoJTextField.getText().length()==0
            ||mThreeJTextField.getText().length()==0
            ||dOneJTextField.getText().length()==0
            ||dTwoJTextField.getText().length()==0
            ||dThreeJTextField.getText().length()==0)
            {
                return false;
            }
        else
        {
            return true;
        }
    }  
    
      private void addStringThenSpaceVerifiers(){
        InputVerifier stringThenSpaceVerifier = new StringThenSpaceVerifier();
        mOneJTextField.setInputVerifier(stringThenSpaceVerifier);
        mTwoJTextField.setInputVerifier(stringThenSpaceVerifier);
        mThreeJTextField.setInputVerifier(stringThenSpaceVerifier);
    }
      
       private void addIntegerVerifiers(){
          InputVerifier integerVerifier = new NumericVerifier();
          dOneJTextField.setInputVerifier(integerVerifier);
          dTwoJTextField.setInputVerifier(integerVerifier);
          dThreeJTextField.setInputVerifier(integerVerifier);
     }
      
      
    public void populatepatientJTable(){
        
        patientDrugJTable.setFont(new Font("Comic Sans MS", Font.BOLD, 10));
        patientDrugJTable.getTableHeader().setFont(new Font("Comic Sans MS", Font.BOLD, 10));
        
        DefaultTableModel model = (DefaultTableModel)patientDrugJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : org.getWorkQueue().getWorkRequestList())
        
        {
            AppointmentVisitRequest req = (AppointmentVisitRequest)request;
            if(req.getReceiver()==userAccount){
                
            Object[] row = new Object[4];
            
            row[0] = req;
            row[1] = req.getSender().getEmployee();
            row[2] = req.getAppointmentDate(); 
            row[3] = req.getStatus1();
            
            model.addRow(row);
        }}
    }
   
       
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestDrugJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mTwoJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        mThreeJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dTwoJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dThreeJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mOneJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dOneJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientDrugJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        requestDrugJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        requestDrugJButton.setText("Request Drug");
        requestDrugJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestDrugJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Medicine 2");

        mTwoJTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        mTwoJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTwoJTextFieldActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Milligram Dosage 2(in mg)");

        mThreeJTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        mThreeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mThreeJTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Medicine 3");

        dTwoJTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Milligram Dosage 3(in mg)");

        dThreeJTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        dThreeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dThreeJTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Medicine 1");

        mOneJTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Milligram Dosage 1(in mg)");

        dOneJTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        dOneJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dOneJTextFieldActionPerformed(evt);
            }
        });

        patientDrugJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Patient", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientDrugJTable);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("DOCTOR TO CHEMIST REQUEST FOR PATIENT'S TESTS:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backJButton)
                                .addGap(145, 145, 145)
                                .addComponent(requestDrugJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(137, 137, 137)
                                        .addComponent(mOneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel1))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dOneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mTwoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dTwoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mThreeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(36, 36, 36)
                                        .addComponent(dThreeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(305, 305, 305))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dOneJTextField, dThreeJTextField, dTwoJTextField, mOneJTextField, mThreeJTextField, mTwoJTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addComponent(mOneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dOneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mTwoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dTwoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(mThreeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dThreeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(requestDrugJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton))
                .addGap(24, 24, 24))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dOneJTextField, dThreeJTextField, dTwoJTextField, mOneJTextField, mThreeJTextField, mTwoJTextField});

    }// </editor-fold>//GEN-END:initComponents

    private void requestDrugJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestDrugJButtonActionPerformed
       
        if(checkBlankInput()){
        int selectedRow = patientDrugJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select A Row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        AppointmentVisitRequest request = (AppointmentVisitRequest)patientDrugJTable.getValueAt(selectedRow, 0);
        
        request.setStatus2("Sent");
     
        String medicine1 = mOneJTextField.getText();
        request.setMedicineOne(medicine1);
        
        String medicine2 = mTwoJTextField.getText();
        request.setMedicineTwo(medicine2);
        
        String medicine3 = mThreeJTextField.getText();
        request.setMedicineThree(medicine3);
        
       
        
        int dosage1 = (Integer.parseInt(dOneJTextField.getText()));
        request.setDosageOne(dosage1);
        
        int dosage2 = (Integer.parseInt(dTwoJTextField.getText()));
        request.setDosageTwo(dosage2);
        
        int dosage3 = (Integer.parseInt(dThreeJTextField.getText()));
        request.setDosageThree(dosage3);
        
    
            Organization org = null;
            Enterprise ent = null;
          
      
        for (Network net : business.getNetworkList()) {
            for (Enterprise enter : net.getEnterpriseDirectory().getEnterpriseList()) {
                if (enter instanceof PharmacyEnterprise) {
                    for (Organization organization : enter.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof ChemistOrganization) {
                            org = (ChemistOrganization) organization;
                            break;
            }
           }
          }
         }
        }
        
        if(org != null)
            {
                
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        
            
            }
          
    JOptionPane.showMessageDialog(null, "Request has been sent to the preferred Chemist.",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
    
    populatepatientJTable();
        }
        
        else{
             JOptionPane.showMessageDialog(null, "Please fill all the values.",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_requestDrugJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorToChemistRequestJPanel dtprjp = (DoctorToChemistRequestJPanel) component;
        dtprjp.populateDrugTable();
               
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void mThreeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mThreeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mThreeJTextFieldActionPerformed

    private void dThreeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dThreeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dThreeJTextFieldActionPerformed

    private void dOneJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dOneJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dOneJTextFieldActionPerformed

    private void mTwoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTwoJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTwoJTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField dOneJTextField;
    private javax.swing.JTextField dThreeJTextField;
    private javax.swing.JTextField dTwoJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mOneJTextField;
    private javax.swing.JTextField mThreeJTextField;
    private javax.swing.JTextField mTwoJTextField;
    private javax.swing.JTable patientDrugJTable;
    private javax.swing.JButton requestDrugJButton;
    // End of variables declaration//GEN-END:variables
}
