/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PathologyLabEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.LabAssistantOrganization;
import Business.UserAccount.UserAccount;
import Business.Queue.AppointmentVisitRequest;
import Business.Queue.WorkRequest;
import Business.Validations.StringThenSpaceVerifier;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zeppelin
 */


public class RequestTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestTestJPanel
     */
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private Network network;
    private Organization org;
   // private UserAccount labAssistant;
    
    public RequestTestJPanel(JPanel userProcessContainer, UserAccount account,
            Enterprise enterprise,Organization org, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        userAccount = account;
        this.business = business;
        this.org=org;

        populatepatientJTable();
        checkBlankInput();
        addStringThenSpaceVerifiers();
        
    }

    private Boolean checkBlankInput()
    {
        if(tOneJTextField.getText().length()==0
            ||tTwoJTextField.getText().length()==0
            ||tThreeJTextField.getText().length()==0)
            {
                return false;
            }
        else
        {
            return true;
        }
    }  
    
    
      private void addStringThenSpaceVerifiers(){
        InputVerifier stringThenSpaceVerifier = new StringThenSpaceVerifier();
        tOneJTextField.setInputVerifier(stringThenSpaceVerifier);
        tTwoJTextField.setInputVerifier(stringThenSpaceVerifier);
        tThreeJTextField.setInputVerifier(stringThenSpaceVerifier);
    }
      
    public void populatepatientJTable(){
        
        patientTestJTable.setFont(new Font("Comic Sans MS", Font.BOLD, 10));
        patientTestJTable.getTableHeader().setFont(new Font("Comic Sans MS", Font.BOLD, 10));
        
     DefaultTableModel model = (DefaultTableModel)patientTestJTable.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : org.getWorkQueue().getWorkRequestList())
        
        {
            AppointmentVisitRequest req = (AppointmentVisitRequest)request;
            if(req.getReceiver()==userAccount){
                
            Object[] row = new Object[4];
            
            row[0] = req;
            row[1] = req.getSender().getEmployee();
            row[2] = req.getAppointmentDate(); 
            row[3] = req.getStatus1();
            
            
            
            model.addRow(row);
        }}
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tOneJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tTwoJTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tThreeJTextField = new javax.swing.JTextField();
        requestDrugJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTestJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Test 1");

        tOneJTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Test 2");

        tTwoJTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tTwoJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTwoJTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Test 3");

        tThreeJTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tThreeJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tThreeJTextFieldActionPerformed(evt);
            }
        });

        requestDrugJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        requestDrugJButton.setText("Request Tests");
        requestDrugJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestDrugJButtonActionPerformed(evt);
            }
        });

        patientTestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Patient", "Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(patientTestJTable);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DOCTOR TO LAB ASSISTANT REQUEST FOR PATIENT'S TESTS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)
                        .addGap(156, 156, 156)
                        .addComponent(requestDrugJButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(161, 161, 161)
                        .addComponent(tOneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(161, 161, 161)
                        .addComponent(tTwoJTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(161, 161, 161)
                        .addComponent(tThreeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(399, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(112, 112, 112)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tOneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9))
                    .addComponent(tTwoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))
                    .addComponent(tThreeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestDrugJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestDrugJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestDrugJButtonActionPerformed
    if(checkBlankInput()){
        
       int selectedRow = patientTestJTable.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select A Row", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
       
         AppointmentVisitRequest request = (AppointmentVisitRequest)patientTestJTable.getValueAt(selectedRow, 0);

         request.setStatus3("Sent");
      
        String test1 = tOneJTextField.getText();
        request.setTestOne(test1);

        String test2 = tTwoJTextField.getText();
        request.setTestTwo(test2);

        String test3 = tThreeJTextField.getText();
        request.setTestThree(test3);
        
        Organization org = null;
        Enterprise ent = null;

        for(Network net : business.getNetworkList())  {
            for (Enterprise enter : net.getEnterpriseDirectory().getEnterpriseList())    {
                if(enter instanceof PathologyLabEnterprise)  {
                    for (Organization organization : enter.getOrganizationDirectory().getOrganizationList())   {
                        if (organization instanceof LabAssistantOrganization){
                            org = (LabAssistantOrganization)organization;
                            break;
                        }
                    }
                }
            }
        }
        if(org != null)
        {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        
        }
        
     JOptionPane.showMessageDialog(null, "Request has been sent to the preferred CLab Assistant.",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
      populatepatientJTable(); 
  
      }
    
    else{

      
      JOptionPane.showMessageDialog(null, "Please fill all fields.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
      }
                   
    }//GEN-LAST:event_requestDrugJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        
        DoctorToLabAssistantRequestJPanel dtlarjp = (DoctorToLabAssistantRequestJPanel) component;
        dtlarjp.populateTestTable();

        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void tTwoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTwoJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTwoJTextFieldActionPerformed

    private void tThreeJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tThreeJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tThreeJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientTestJTable;
    private javax.swing.JButton requestDrugJButton;
    private javax.swing.JTextField tOneJTextField;
    private javax.swing.JTextField tThreeJTextField;
    private javax.swing.JTextField tTwoJTextField;
    // End of variables declaration//GEN-END:variables
}
